### ISSUE TITLE
CIF Reports

### ISSUE THREAD

**Issue by tgorup** [csirtgadgets/cif-v1#84]
Receiving the following error message when running cif-feeds-report. I'm not familiar with Perl, did I miss a package someplace? Google searches have came up empty.

```
$ cif-feeds-report -h
Can't locate CIF/Archive/DataType/Plugin/Feed/Search.pm in @INC (@INC contains: /opt/cif/bin/../../libcif/lib /opt/cif/bin/../local/lib /opt/cif/bin/../lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /opt/cif/bin/cif-feeds-report line 36.
```

Not sure if I should be starting a different thread for this, but figured it was also a reporting issue. cif-query-report is coming up empty. I've been testing this out quite a bit and would assume there would be data here.

```
$ cif-query-report -t 2015-02-28 -n
Report Window: 2015-02-28T00:00:00Z - 2015-03-01T19:43:13Z

count source
```

Let me know if you need any further information.

**Comment by wesyoung** [comment]
sorry about missing this one, is /opt/cif/.. your $PATH for the user you're running this under? do other cif like commands work?
